### ISSUE TITLE
Error when running HAM evaluation script

### ISSUE THREAD

**Issue by zorikg** [princeton-nlp/EvalConvQA#3]
Hi, 

I tried to run `HAM` evaluation script and got the following error from `.../EvalConvQA/models/ham/cqa_model.py`:
```
Traceback (most recent call last):
  File ".../EvalConvQA/run_quac_eval.py", line 704, in <module>
    main()
  File ".../EvalConvQA/run_quac_eval.py", line 591, in main
    model = model_class(args=args)
  File ".../EvalConvQA/models/ham/interface.py", line 78, in __init__
    self.slice_num, self.args)
  File ".../EvalConvQA/models/ham/cqa_model.py", line 288, in fine_grained_history_attention_net
    token_tensor.set_shape([FLAGS.train_batch_size, FLAGS.max_history_turns, FLAGS.max_seq_length + 1, FLAGS.bert_hidden])
  File "/Users/.../opt/anaconda3/envs/cqa_eval/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 559, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 3 in both shapes must be equal, but are 768 and 1024. Shapes are [16,?,513,768] and [16,11,513,1024].
```

Could you please assist?

**Comment by huihanlhh** [comment]
Hi,

The model checkpoint was trained with bert-large, so please check FLAGS.bert_hidden to be 1024 as well.

Let me know if the issue persists.
